### ISSUE TITLE
Make it unavailable for user to add reminders if there's no permission given to the app

### ISSUE THREAD

**Issue by lesterrry** [Fetch-Development/Jay#9]
So far I can press "+" and add new reminder, but it won't be shown anywhere, which may be unclear for users.

**Comment by lesterrry** [comment]
But I **DO** want to add reminder through app, you haven't fixed anything but removed the feature

**Comment by otter18** [comment]
Chatting here now. Cool...

**Comment by lesterrry** [comment]
> Chatting here now. Cool...

yep why not
